#+TITLE: number-detection

Short evaluation of number detection performance on [[https://github.com/skit-ai/phone-number-entity-dataset][phone-number-entity-dataset]]
for a few ASR systems. The dataset has simple utterances but in Indian English
which should show up some challenges.

The dataset above has significant label noise. For this experiment, I fixed the
labels (only for the single turn dataset) manually and have added the corrected
label file in this repository.

** Single Turn Dataset
SER (Sentence Error Rate) is the primary metric telling the quality of one shot
detection for full number pattern.

WER roughly maps to CER (Character Error Rate) since we normalize each digit as
separate word before WER calculation.

|--------------------+--------------------------+--------+----------|
| Model              | Model Spec               |    SER | Mean WER |
|--------------------+--------------------------+--------+----------|
| Deepgram - Offline | ~nova-2-general~, ~en-IN~    | 0.1507 |   0.0230 |
| Deepgram - Offline | ~nova-2-phonecall~, ~en~     | 0.1164 |   0.0178 |
| Whisper - Offline  | ~large-v3~                 | 0.2192 |   0.1206 |
| Google - Offline   | ~telephony_short~, ~en-IN~ | 0.3973 |   0.0558 |
| Google - Offline   | ~chirp_2~, ~en-IN~           | *0.0411* |   *0.0048* |
|--------------------+--------------------------+--------+----------|

All the models above are used in offline mode which will have generally better
performance than streaming systems. Streaming numbers will be added later.

To reproduce, assuming you have extracted the dataset in ~./data~,

#+begin_src shell
  # You will need to install torch (in the poetry venv) along with general poetry install
  poetry run python scripts/transcribe.py whisper ./data/single-turn-dataset/data --output-csv=output-whisper.csv
  # Set up DEEPGRAM_API_KEY for this
  poetry run python scripts/transcribe.py deepgram ./data/single-turn-dataset/data --output-csv=output-dg-prerecorded.csv
  # Set up Gcloud credentials
  poetry run python scripts/transcribe.py google ./data/single-turn-dataset/data --output-csv=output-google-chirp-2.csv

  # Replace the file you want to evaluate
  poetry run python scripts/evaluate.py ./data/single-turn-dataset/single-turn-data.csv ./output-dg-prerecorded.csv
#+end_src
