#+TITLE: number-detection

Short evaluation of number detection performance on [[https://github.com/skit-ai/phone-number-entity-dataset][phone-number-entity-dataset]]
for a few ASR systems. The dataset has simple utterances but in India English
which should show up some challenges with various ASR systems.

* Single Turn
SER (Sentence Error Rate) is the primary metric telling the quality of one shot
detection for full number pattern.

WER roughly maps to CER (Character Error Rate) since we normalize each digit as
separate word before WER calculation.

|----------------------------+---------------------------------+--------+------------+----------|
| Model                      | Model Spec                      |    SER | Median WER | Mean WER |
|----------------------------+---------------------------------+--------+------------+----------|
| [[https://github.com/skit-ai/SpeechLLM/tree/f44d361277ae5e2fa687b39f861f630ca2571318][Speech LLM 2B - Offline]]    | NA                              | 0.8082 |       0.20 |   1.5572 |
| Deepgram Nova-2 - Offline  | General, en-IN, smart format on | 0.4658 |        0.0 |   0.2364 |
| Deepgram Nova-2 - Offline  | Phonecall, en, smart format on  | 0.4384 |        0.0 |   0.2336 |
| Whisper Large v3 - Offline |                                 | 0.3973 |        0.0 |      0.3 |
|----------------------------+---------------------------------+--------+------------+----------|

> [!NOTE]
> All the models above are used in offline mode which will have generally better
> performance than streaming systems. Streaming numbers will be added later.

To reproduce, assuming you have extracted the dataset in ~./data~,

#+begin_src shell
  # You will need to install torch and torchaudio (in the poetry venv) along with general poetry install
  poetry run python scripts/transcribe.py speechllm ./data/single-turn-dataset/data --output-csv=output-speech-llm.csv

  # Set up DEEPGRAM_API_KEY for this
  poetry run python scripts/transcribe.py deepgram ./data/single-turn-dataset/data --output-csv=output-dg-prerecorded.csv
  poetry run python scripts/transcribe.py whisper ./data/single-turn-dataset/data --output-csv=output-whisper.csv

  # Replace the file you want to evaluate
  poetry run python scripts/evaluate.py ./data/single-turn-dataset/single-turn-data.csv ./output-dg-prerecorded.csv
#+end_src

* Two Turns
~NA~
